### ISSUE TITLE
using the js example from the browser results in failed preflight request

### ISSUE THREAD

**Issue by ptica** [iiw/Crex24.Examples#1]
OPTIONS https://api.crex24.com/CryptoExchangeService/BotTrade/ReturnBalances 405 ()
localhost/:1 Failed to load https://api.crex24.com/CryptoExchangeService/BotTrade/ReturnBalances: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3006' is therefore not allowed access. The response had HTTP status code 405.

**Comment by iiw** [comment]
Ok, thanks, will check in this week

**Comment by developer9851** [comment]
@ptica cross-origin requests are not allowed for authenticated endpoints (such as https://api.crex24.com/CryptoExchangeService/BotTrade/ReturnBalances) for security reasons. Consequently, one can not invoke authenticated methods directly from a browser. Most likely this won't change in the nearest future. Sorry for the inconvenience.
