### ISSUE TITLE
Status code: 401 {"errorDescription":"Failed to verify request signature."}

### ISSUE THREAD

**Issue by Bitcoinera** [iiw/Crex24.Examples#5]
Hello. I have been using your code, concretely pythonv2 and node, but both are giving me the error of the title. I was getting errors related to padding with base64 and also with 'bytes' against 'str' format, so I had to make a workaround to solve this. My code to create the key, message and signature with python3  now looks like this:

keybytes = base64.b64encode(secret.encode())
key = base64.b64decode(keybytes)
message = str.encode(path + str(nonce), "utf-8")
hmac= hmac.new(key, message, sha512)
signature = base64.b64encode(hmac.digest()).decode()

I tried many things, like adding and retrieving 'utf-8' in encode() and decode(), tried typing the b64 operations differently, looked into my timestamp by running the code from a VPS, using different python3 versions... If you have any idea I will be happy to listen. It's clearly a base64 issue. Also present in nodejs. What version&environment are you using?

**Comment by iiw** [comment]
There is new api version https://docs.crex24.com/trade-api/v2/ 
I didn't updated examples for it. And I don't know api v1 still available or not.

**Comment by Bitcoinera** [comment]
I think it is not.. I used the examples from the official page but still getting the same error with the signature. I'll add your repository in the Watch list in case you update it some time
